# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dad13ad0304b25c6795379e0698401f7f75b19a29d62a22d70e86c6d61cb7d4140e7679621c65c4a47a10d6ae5cd915c325906aa085ae42f788c1ca37cb1613a




test:
  secret_key_base: 8263ff6b43401b75f69712a1c6e4914f82f6f2991d11d9a1ec805038b66a061aa11a5651a257b7b83473ed5dbe4de1e76445117d5e0fd6228397a289b62c2440


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
